import Head from 'next/head'
import styles from '../styles/Home.module.css'

import axiosPublic from "@monorepo/axios-config";

export async function getStaticProps() {
    const { data } = await axiosPublic.get('https://pokeapi.co/api/v2/pokemon/pikachu')

    return {
        props: {
            pokemonInfo: data,
        },
    }
}


export default function Home({ pokemonInfo }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <pre>PROJECT: PRODUTOR</pre>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a>, <strong>{ pokemonInfo.name }</strong> !!!
        </h1>
      </main>
    </div>
  )
}
